name: Build and test data package

on:
  pull_request:
    # Run on PRs to any branch
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v2
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install h5py dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev

      - name: Install dependencies
        run: |
          uv sync --python ${{ matrix.python-version }} --extra dev

      - name: Test with pytest
        run: |
          uv run pytest --cov=macro_data tests/test_macro_data --cov-report xml
